### ISSUE TITLE
Permission file for linux server

### ISSUE THREAD

**Issue by pakeidoprek** [BlackrockDigital/startbootstrap-sb-admin-2#108]
sorry, ia have problem to load css file in my admin template. do you have permission code to make it this template work ?
![screenshot from 2016-03-16 20 57 41](https://cloud.githubusercontent.com/assets/15980134/13812941/c3561062-ebb9-11e5-9dd3-0792b02ff97f.png)

**Comment by mitchellurgero** [comment]
try: sudo chmod -R 0644  /var/www

**Comment by davidtmiller** [comment]
Thanks @mitchellurgero - hopefully that solved the issue!
