### ISSUE TITLE
An error occured  when installing 

### ISSUE THREAD

**Issue by mscgla** [BlackrockDigital/startbootstrap-sb-admin-2#115]
Hi

I tried to install this package in visual studio 2015 community edition using (Manage Bower package) and i am getting the following error. 

I also tried to run the visual studio in Administrator mode and getting the same error.

I click on yes and including the output window details.

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\Bower.cmd" install startbootstrap-sb-admin-2# --production --force-latest --save
bower startbootstrap-sb-admin-2#*       not-cached https://github.com/IronSummitMedia/startbootstrap-sb-admin-2.git#*
bower startbootstrap-sb-admin-2#*          resolve https://github.com/IronSummitMedia/startbootstrap-sb-admin-2.git#*
bower startbootstrap-sb-admin-2#*         checkout v1.0.8
bower startbootstrap-sb-admin-2#*          ECMDERR Failed to execute "git clone https://github.com/IronSummitMedia/startbootstrap-sb-admin-2.git -b v1.0.8 --progress . --depth 1", exit code of #-532462766

![image](https://cloud.githubusercontent.com/assets/4937068/14952532/f18d2b82-1058-11e6-9032-61f76ff66a6d.png)

**Comment by davidtmiller** [comment]
Referenced in #117

**Comment by Towesco16** [comment]
Visual studio 2017  does support bower  any more
