### ISSUE TITLE
bower install fails: ENORESTARGET  Tag/branch eef80ed does not exist

### ISSUE THREAD

**Issue by ifrade** [BlackrockDigital/startbootstrap-sb-admin-2#117]
All these commands:
$ bower install startbootstrap-sb-admin-2
$ bower install https://github.com/BlackrockDigital/startbootstrap-sb-admin-2.git
$ bower install startbootstrap-sb-admin-2#1.0.8
$ bower install startbootstrap-sb-admin-2#1.0.7 

Fail with the following log:
...
bower cached        https://github.com/jquery/jquery-dist.git#2.2.3
bower validate      2.2.3 against https://github.com/jquery/jquery-dist.git#>= 1.2.6
bower not-cached    https://github.com/adobe-webplatform/eve.git#eef80ed
bower resolve       https://github.com/adobe-webplatform/eve.git#eef80ed
bower cached        https://github.com/jquery/jquery-dist.git#2.2.3
bower validate      2.2.3 against https://github.com/jquery/jquery-dist.git#1.9.1 - 2
bower ENORESTARGET  Tag/branch eef80ed does not exist

Additional error details:
Available tags: v.0.1.2, v0.1.1, v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4
Available branches: master
$

Looks like the adobe-webplatform commit is fixed somewhere to a wrong commit id. I tried bower cache clean and removing ~/.cache/bower but it didn't help.

**Comment by davidtmiller** [comment]
Closing this - reference the most recent update I posted in #130 for more info!
