### ISSUE TITLE
plug to RESTful API

### ISSUE THREAD

**Issue by worldofpiggy** [BlackrockDigital/startbootstrap-sb-admin-2#118]
Is there a good example to plug this dashboard to a RESTful API?
I am struggling with the login service and connector to authenticate with json...
I have no clue what I am doing wrong and an example would help. 
Thanks in advance

**Comment by davidtmiller** [comment]
I don't have an answer for you here unfortunately. If anyone wants to chime in on this one I'll mark it as a question!

**Comment by gabrielacosta** [comment]
There is a way to do it. You can add an httpclient in the controller and make a call to the external API. Of course, you need to add the proper authorization headers. I'm still checking the performance issues, but so far I think it works fine.
