### ISSUE TITLE
jQuery UI support?

### ISSUE THREAD

**Issue by TomThak** [BlackrockDigital/startbootstrap-sb-admin-2#119]
Are you going to support jQuery UI themes? If I use any of the jQuery UI elements like Tabs, Accordeon, Dialog, DatePicker it would be nice if it will use the same CSS styles like other elements of your theme.

**Comment by tiesont** [comment]
Historically, Bootstrap and jQuery UI tend to conflict (they use some of the same class names, I believe, and Bootstrap's CSS reset tends to bork the layout on some of UI's widgets), so it may be hard to support them. You *might* be able to use http://jquery-ui-bootstrap.github.io/jquery-ui-bootstrap/, but it hasn't been updated in a little while.

*Disclaimer: I'm not a dev on this repo. I use it on occasion and have seen the above issue when using BS and jQuery UI together, so seemed worth chiming in.*

**Comment by TomThak** [comment]
I understand, If I remember it right it was mainly the problem of .dialog() and .tabs(). I have already tried themed jQuery UI. It means to use bootstrap + include jquery UI + themes, but exclude the bootstrap JS.

**Comment by TomThak** [comment]
I found this solution: http://www.ryadel.com/en/using-jquery-ui-bootstrap-togheter-web-page/

This should work, so both libraries should work simultaneously. The only problem will be to redefine all CSS of jQuery UI smoothnes.css file and change it / assign it to your styles. Because in your stylesheet you have created custom styling of the elements and it would be nice if jQuery UI will apply the same rules, so for example jQuery UI Tabs will look 100% the same like Bootstrap tabs etc. I will try to do it myself.

**Comment by davidtmiller** [comment]
Thanks @TomThak for the solution.

**Comment by TomThak** [comment]
We tested it and it works.
