### ISSUE TITLE
dataTables.responsive.css doesn't exist in static files

### ISSUE THREAD

**Issue by NBajanca** [BlackrockDigital/startbootstrap-sb-admin-2#122]
dataTables.responsive.css doesn't exist in static files. In bower components the css directory of datatables-responsive doesn't have the css required giving **404 (Not Found)**
I have solved this by:
`<link` href="https://cdn.datatables.net/responsive/2.1.0/css/responsive.dataTables.min.css" `rel="stylesheet">`

**Comment by davidtmiller** [comment]
Thanks for the fix. I am going to redo a lot of things with this template when I have the time, and making sure all of the plugins are up to date and fresh is one of the first things on the list.

**Comment by ntaback26** [comment]
DataTable responsive may be not working :(

**Comment by davidtmiller** [comment]
DataTables plugin was updated and moved into a new `vendor` directory. Everything seems to be loading properly now. #134
