### ISSUE TITLE
"Graph container element not found" when using angularJS and ui router to load the morris chart in the index.html

### ISSUE THREAD

**Issue by lindholmen** [BlackrockDigital/startbootstrap-sb-admin-2#124]
Hi,

I found that all html pages are using the same code to construct the navbar and side bar. The difference is the things in the "page wrapper". So i wrap all the navbar code into a header.html and wrap all the other page content into a content.html and accordingly I use the ui router to introduce two ui view *(e.g. <div ui-view="header"></div><div ui-view="content"></div>) in the index.html so that I can specify their states-view-controller-templateURL in the app.js.

`state('app', {
                url:'/',
                views: {
                    'header': {
                        templateUrl : 'views/header-test.html',
                        controller: "HeaderController"
                    },
                    'content': {
                        templateUrl : 'views/content-test.html',
                        controller  : 'PageContentController'
                    }
                }
            })` 

The problem is if i left all the reference code to the javascripts modules at the bottom of the index.html, the page would not rendered successfully...
I tried to use the $ocLazyLoad to load the necessary JS modules in the corresponding controllers, but it still does not work..and give me this error "Graph container element not found"...I want to load the raphael, morris and morris-data js files after I have create the DOM for the status of "content".  How can i solve this issue?

Thanks!

**Comment by davidtmiller** [comment]
I am not exactly sure how to fix this up as I don't have much experience using JS frameworks. If anyone wants to chime in on this one feel free!

**Comment by juanpablolopez** [comment]
Hi, maybe is late but I have added the <script src="morris.min.js" /> at the end of in the same file that angular loads with the route
