### ISSUE TITLE
Can update bower dependency to font-awesome to 4.6.3?

### ISSUE THREAD

**Issue by ssteinerx** [BlackrockDigital/startbootstrap-sb-admin-2#126]
4.2.0 was released on Aug 26, 2014.

If any bower component specifies 4.6.3 (released on May 13, 2016), then 4.6.3 will get pulled in anyway, so there doesn't seem to be a downside to updating.

I haven't noticed any problems, but maybe I don't know exactly where to look...

**Comment by nelson6e65** [comment]
You can "override" the FA version in your own `bower.json` and marking resolution. Something like:

```json
{
  "dependencies": {
    "font-awesome": "^4.6.0",
    "startbootstrap-sb-admin-2": "BlackrockDigital/startbootstrap-sb-admin-2#^1.0.7",
  },
  "resolutions": {
    "font-awesome": "^4.6.0"
  }
}
```

**Comment by nelson6e65** [comment]
You can "override" the FA version in your own `bower.json` and marking resolution. Something like:

```json
{
  "dependencies": {
    "font-awesome": "^4.6.0",
    "startbootstrap-sb-admin-2": "BlackrockDigital/startbootstrap-sb-admin-2#^1.0.7",
  },
  "resolutions": {
    "font-awesome": "^4.6.0"
  }
}
```

**Comment by davidtmiller** [comment]
I will need to re-register this repo with Bower and npm just to get this fixed up.

**Comment by davidtmiller** [comment]
Updated in #135
