### ISSUE TITLE
flickering font-awesome icons

### ISSUE THREAD

**Issue by dkengaroo** [BlackrockDigital/startbootstrap-sb-admin-2#127]
It seems that the font-awesome icons have a bit of a pause on load.

I pulled this template a couple months back and the transition between tabs on the side-nav were seamless and smooth. There wasn't a flickering of reloading the icons.

It seems that in this current version of the live demo, the font awesome icons have a pause before loading and also all the side nav tabs open up before closing again.

**Comment by davidtmiller** [comment]
I'll check into this thanks.

**Comment by davidtmiller** [comment]
It may be that the dependency was just loading a bit slowly. I don't really have a fix for making the icons load faster unfortunately.
