### ISSUE TITLE
side bar scroll

### ISSUE THREAD

**Issue by fecc82** [BlackrockDigital/startbootstrap-sb-admin-2#128]
Side bar dont show scroll when browser size is less to bar height, this is hidden. thanks for your help.

**Comment by davidtmiller** [comment]
Can you elaborate a little bit on this one?

**Comment by fecc82** [comment]
When the lateral menu is higher than the window size does not appear scroll to display the options at the end of the menu ; the content exceeds the window is being hidden and you can not select these options. In the version startbootstrap -sb -admin" scroll the menu works correctly .

![compare_ver](https://cloud.githubusercontent.com/assets/20919649/17831581/34d05e14-66b2-11e6-9934-238ce3230eb1.jpg)

![compare_ver](https://cloud.githubusercontent.com/assets/20919649/17831577/24d7b354-66b2-11e6-94b6-86c1be5f044b.jpg)
