### ISSUE TITLE
removed from bower and npm?

### ISSUE THREAD

**Issue by leftstick** [BlackrockDigital/startbootstrap-sb-admin-2#129]
I found that `npm` and `bower` shows information as following:

![screen shot 2016-08-10 at 2 12 39 pm](https://cloud.githubusercontent.com/assets/1059956/17543628/85976d16-5f04-11e6-8ad9-8f6912c8585d.png)

![screen shot 2016-08-10 at 2 12 58 pm](https://cloud.githubusercontent.com/assets/1059956/17543638/9a1ebd7a-5f04-11e6-8925-b1dc28b9b4ed.png)

The URL pointed to another place which is [https://github.com/ironsummitmedia/startbootstrap-sb-admin-2](https://github.com/ironsummitmedia/startbootstrap-sb-admin-2)

And no `tag`, no useful code there, is there something bad happened?

**Comment by lwrbakro** [comment]
why?

**Comment by nelson6e65** [comment]
I wondering the same thing... 
#130

**Comment by davidtmiller** [comment]
Not sure why this happened but it's the wrong link as well. I will re-register the repo with Bower and npm to get this fixed up soon.

**Comment by davidtmiller** [comment]
Closing this. Refer #130
