### ISSUE TITLE
Active menu item not set when there is a query string

### ISSUE THREAD

**Issue by FilipQL** [BlackrockDigital/startbootstrap-sb-admin-2#133]
Hi,

when there is a query string in URL -  sidebar doesn't have active menu item. For example, I have:

```
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="/tags"><i class="fa fa-tags fa-fw"></i> Tags</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
```

and when I open **example.com/tags** - that menu item will be active. But when I open: **example.com/tags?page=2** - it isn't active. Do you have any suggestions on how can I handle this?

**Comment by davidtmiller** [comment]
`sb-admin-2.js` line 32 returns the url and line 33 sets the parent as active. You would need to change that return in line 32 to grab just the first part of the url. I'm not a super JS wizard so I'm not sure how to do this, but I am pretty sure that's exactly what needs to be done.
