### ISSUE TITLE
How to have Datatable scroll horizontally

### ISSUE THREAD

**Issue by smark111** [BlackrockDigital/startbootstrap-sb-admin-2#148]
On the Tables page, we want to avoid having Responsive feature of having columns hidden. So we disabled following,

    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            //responsive: true -- Commented this line
        });
    });
    
The only issue when page size reduces then table columns are going outside panel.

Instead we want to have Datatable show horizontal scroll bar, and page should not have horizontal scroll bar.

Can you please suggest what changes we need to make on HTML page to have only table scroll and not the atual page.

Thanks
![Uploading table_columns_outside.png…]()

**Comment by smark111** [comment]
Another screen capture showing the issue.

![table_columns](https://cloud.githubusercontent.com/assets/5794863/18397327/4c4ceff6-76e5-11e6-93e4-963e10d512c8.png)

Any solution to this will be appreciated.
Thanks

**Comment by smark111** [comment]
Found solution. Need to wrap table in <div class="table-responsive"></div>

**Comment by dendihandian** [comment]
> Found solution. Need to wrap table in

@smark111 How did you accomplish this? Can you provide the HTML and JS example?

@davidtmiller I need help here

**Comment by codeplotter** [comment]
@dendihandian Did you find the answer to this?

**Comment by dendihandian** [comment]
> @dendihandian Did you find the answer to this?

I did, but I can't remember because the code is in a company's private repo. I think it solved as someone stated above about wrapping it in a div.

**Comment by codeplotter** [comment]
I had tried a whole bunch of things, including copying/pasting an example that should work... after a few hours, out of desperation I just restarted Chrome, and the problem was gone :-\

Thanks for the reply!


On Apr 11, 2022, at 12:56 AM, Dendi Handian ***@***.***> wrote:


@dendihandian <https://github.com/dendihandian> Did you find the answer to this?

I did, but I can't remember because the code is in a company's private repo. I think it solved as someone stated above about wrapping it in a div.

**Comment by dendihandian** [comment]
@codeplotter be careful of browser cache. If your css code aren't versioned everytime you change a style, make sure to hard refresh the page.

**Comment by codeplotter** [comment]
Yep, I was doing that - and CSS changes were made inline.  Hard to say what happened.

On Apr 11, 2022, at 11:57 AM, Dendi Handian ***@***.***> wrote:


@codeplotter <https://github.com/codeplotter> be careful of browser cache. If your css code aren't versioned everytime you change a style, make sure to hard refresh the page.
