### ISSUE TITLE
Force "collapse" Navbar on alle Screenwidth

### ISSUE THREAD

**Issue by zwantE** [BlackrockDigital/startbootstrap-sb-admin-2#149]
Hey,
is it possible to force "collapse" Navbar an all Screenwidth?

in specialy, i have a subsite that needs full screen width and so i want collapse the navbar on it.

**Comment by jantman** [comment]
Yes, it is. See ``sb-admin-2.js``; that javascript controls collapsing the navbar based on screen width.
