### ISSUE TITLE
How to remove left column?

### ISSUE THREAD

**Issue by ochompsky** [BlackrockDigital/startbootstrap-sb-admin-2#156]
How do I remove the left column and just have the dashboard and header?  I've pretty much strippedout all the code but it's still there.

**Comment by sinfuljosh** [comment]
I copied the "blank.html" from pages and removed the left side bar nav code. 

https://gist.github.com/sinfuljosh/0d1e6436a8504598bd30aa9ec17a0e66

Have not made any changes to css or js. Its to show you the section of html that is generating the the side bar.

**Comment by ochompsky** [comment]
Thanks @sinfuljosh 

Looks like the 'page-wrapper' div is the one with the css to modify.  Removing it took care of things, thanks!
