### ISSUE TITLE
SB Admin 2 bootstrap theme compatibility probleme with fonawsome 

### ISSUE THREAD

**Issue by ibti90** [BlackrockDigital/startbootstrap-sb-admin-2#162]
When i install yii advanced application and bootstrap theme SB Admin 2 and after i map the view to the new theme, i got this error : Declaration of p2made\helpers\base\FontAwesome::s() should be compatible with rmrevin\yii\fontawesome\FontAwesome::s($options = Array).
Can any one help me and tell me the way to solve this issue.
Thanks in advance

**Comment by davidtmiller** [comment]
Should no longer be an issue with the most recent version 4 release.
