### ISSUE TITLE
Update font-awesome

### ISSUE THREAD

**Issue by Eddieative** [BlackrockDigital/startbootstrap-sb-admin-2#166]
How to update font-awesome from 4.6.3 to 4.7.0?
Thank you

**Comment by 213edu** [comment]
pretty sure you can just go on [Font Awesome](http://fontawesome.io/) to download the zip, and then extract and replace it at `./vendor/font-awesome/`

**Comment by davidtmiller** [comment]
Font awesome should remain updated at this point.
