### ISSUE TITLE
Collapse side menu bar on responsive view

### ISSUE THREAD

**Issue by Cloves23** [BlackrockDigital/startbootstrap-sb-admin-2#167]
The side menu doesn't work properly using the responsive option from web browser. To solve the problem I added the classes **collapsed** in line 45 and **collapse** in line 266 (you can use the file **index.html** as reference). I've noticed the problem when I reloaded the page using the responsive mode (Firefox: Ctrl + Shift + M).

> Line 45
```html
<button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    ...
</button>
```

> Line 266
```html
<div class="collapse sidebar-nav navbar-collapse">
    ...
</div>
```

**Comment by jantman** [comment]
There is a pull request open to fix this (and a number of duplicate issues), #174. If you're interested in trying it, take a look at the single commit, https://github.com/fabiang/startbootstrap-sb-admin-2/commit/1fdbfd134a2f77c7b345053ca4ef155b51c91a29

**Comment by davidtmiller** [comment]
Responsive collapsing is now supported in version 4.
