### ISSUE TITLE
Need to organized well

### ISSUE THREAD

**Issue by koushik72** [BlackrockDigital/startbootstrap-sb-admin-2#169]
I am really sorry to say it but the entire js and css codes are not organized well. JS should be organized using module bundler like webpack. So that one knows which one to load for which page and css should be organized using sass or less. There is SASS but it's all in one file. It should be split into different files so that I know when to load which file. 
When I wanna start afresh, if I load the plain_page.html, it has custom css and custom js and now these two files over 100kb each and has a lot of things that I simply don't need. So removing them manually makes it very difficult and when something gets messed up while doing it, it messes up the entire thing.
Please use module bundler like webpack and Sass to organize the js and css codes. Otherwise, it's very hard to manage them.

**Comment by davidtmiller** [comment]
SCSS is now being used to organize the code, npm for dependencies, but the JS is free because a lot of people may be rewriting and dropping jQuery due to modern dev frameworks. Version 4 is better organized, and will continue to improve from here!
