### ISSUE TITLE
Hamburger menu on iPhone always open?  Requires two taps to hide.

### ISSUE THREAD

**Issue by jkoerber22** [BlackrockDigital/startbootstrap-sb-admin-2#170]
There seems to be both a bug, and possibly a "feature" to this behavior.

When I view any of the core template pages on my iPhone 6s (xs size) or in a resized web browser (tested in Chrome and Safari), the hamburger menu (HM) options start open (except on the dashboard page for some reason).  

BUG: Clicking the HM opens the menu again, overlaying the currently open menu with the same thing.  Clicking it a second time finally closes the menu.  This seems to be a bug in the JS not recognizing the menu as already open the first time?  This also happens if I shrink my screen on my iMac small enough to trigger the responsive HM.

FEATURE?:  The menu when open and clicked stays open.  My assumption on the proper user interface function is for the menu to start closed until tapped, and then after a selection is made, close itself.  This may be personal preference, so maybe there is a workaround JS call or label that can force the menu to collapse after a selection and upon a page loading.

Here is a vide showing the behavior of the BUG portion above: https://dl.dropboxusercontent.com/u/8557777/2017-03-14_12-55-26.mp4

**Comment by jkoerber22** [comment]
Maybe starting the menu collapsed on page load or reload would solve both problems above.  Maybe there is some JS or tags that can tell the menu to collapse on page load?  Worth a try.

**Comment by jkoerber22** [comment]
Followup: I happened to go back and look at the demo of SB Admin (original version) and its dropdown hamburger menu does not have the same problems that SB Admin 2 has.  Maybe that version of CSS/JS for the menus can replace the one in SBA2?

**Comment by jantman** [comment]
There is a pull request open to fix this (and a number of duplicate issues), #174. If you're interested in trying it, take a look at the single commit, https://github.com/fabiang/startbootstrap-sb-admin-2/commit/1fdbfd134a2f77c7b345053ca4ef155b51c91a29

**Comment by davidtmiller** [comment]
Menu refactored in version 4 of this theme and this should no longer be a problem.
