### ISSUE TITLE
footer height not set when too small... that's incorrect.

### ISSUE THREAD

**Issue by AlexisWilke** [BlackrockDigital/startbootstrap-sb-admin-2#171]
Two notes about the following:

        if (height < 1) height = 1;
        if (height > topOffset) {
            $("#page-wrapper").css("min-height", (height) + "px");
        }

1. The minimum height can be set to 0 since that's the default and it's very similar to not having a minimum height parameter at all.
2. The minimum height has to always be set in the `#page-wrapper`, otherwise we run in all sorts of weird problems when it gets rather small (which is easy to reach when using a smart phone.)

I would suggest the following instead:

        if (height < 0) height = 0;
        $("#page-wrapper").css("min-height", (height) + "px");

Also, if you want to go further, someone (like me) could end up changing the height of the top navigation bar. Your code assumes it is 51 or 101. You should instead retrieve the height after you defined whether the `collapse` class should be set.

        var topOffset = 50;
        var width = (this.window.innerWidth > 0) ? this.window.innerWidth : this.screen.width;
        if (width < 768) {
            $('div.navbar-collapse').addClass('collapse');
            topOffset = 100; // 2-row-menu
        } else {
            $('div.navbar-collapse').removeClass('collapse');
        }

The `topOffset` can be set after the `if()` block using `outerHeight()` and that means you can use the `toggleClass()` to define the current status of the class:

         $('div.navbar-collapse').toggleClass('collapse', width < 768);
    
         topOffset = $("nav.navbar-static-top").outerHeight();

With that, I can change my navigation bar to whatever height I want, and the script picks it up (i.e. If I want to remove the "User" menu from the second line, maybe I move it to the first line, then the height is not 101 on my phone...)

**Comment by davidtmiller** [comment]
This should be resolved in the new version 4 - flexbox and CSS variables will guarantee the height remains constant and the position remains sticky at the bottom.
