### ISSUE TITLE
Metis Menu collapse in chrome and opera, when you visit some page

### ISSUE THREAD

**Issue by offline-online** [BlackrockDigital/startbootstrap-sb-admin-2#18]
If you open [sb-admin-2 demo](http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/) in google chrome, and try to visit any page of the left sidebar, you will notice that sidebar menu will collapse for a moment and then become normal ( this is happening in my apps too ). It is very annoying for users. Is there any way to prevent this from happening ? Thanks

**Comment by leografx** [comment]
add collapse to hide the second-level-menu 
<ul class="nav-second-level collapse">
and your problem will go away.

**Comment by kspearrin** [comment]
Thanks @leografx. That solves it
