### ISSUE TITLE
How to use panel styles

### ISSUE THREAD

**Issue by y80x86ol** [BlackrockDigital/startbootstrap-sb-admin-2#180]
I saw a feature on home page,like this:{"3 custom panel styles"=>"red, yellow, and green"}.
I want to know how to use this panel styles,I don't find the example code.

Thanks!

**Comment by kpmdelosreyes** [comment]
+1

**Comment by tiesont** [comment]
Are you referring to the the different panels at the top of [this demo](https://blackrockdigital.github.io/startbootstrap-sb-admin-2/pages/index.html)? If so, did you inspect the markup? It's fairly straight-forward:

```html
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="row">
            <div class="col-xs-3">
                <i class="fa fa-comments fa-5x"></i>
            </div>
            <div class="col-xs-9 text-right">
                <div class="huge">26</div>
                <div>New Comments!</div>
            </div>
        </div>
    </div>
    <a href="#">
        <div class="panel-footer">
            <span class="pull-left">View Details</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
        </div>
    </a>
</div>
```

Simply put, the colors follow the same pattern as Bootstrap's buttons and alerts.

**Comment by davidtmiller** [comment]
Panels have been dropped as of Bootstrap 4, and in version 4 of this theme we're now using card markup.
