### ISSUE TITLE
Responsive Timeline panels squish when viewing in mobile

### ISSUE THREAD

**Issue by nanomosfet** [BlackrockDigital/startbootstrap-sb-admin-2#181]
![image](https://cloud.githubusercontent.com/assets/21000341/26376197/92657fcc-3fc0-11e7-8af6-921fdaff499a.png)

The image above was taken with google devtools. The view was taken with galaxy note II

**Comment by foohonpie** [comment]
There's a workaround mentioned here:

https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/issues/141#issuecomment-260421076

**Comment by Kelemu** [comment]
Just change the dist\css\sb-admin-2.css file on line 410, 411,412 to
width: calc(85%);
width: -moz-calc(85%);
width: -webkit-calc(85%);
it will work fine

**Comment by davidtmiller** [comment]
This has been removed as of version 4. I may add the timeline back in at some point, but restyled in a new way.
