### ISSUE TITLE
Dynamically adding menu item wont toggle in sidebar-nav

### ISSUE THREAD

**Issue by deslikespizza** [BlackrockDigital/startbootstrap-sb-admin-2#185]
Hi,

Im having a problem menu item added to the sidebar-nav dynamically which wont toggle / collapse.

Ive stripped down the dashboard page example which has an example drop down menu item.

         <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#" id="navbar_brand">SB Admin v2.0</a>
            </div>
            

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
				<a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    
                </li>
                
            </ul>
            

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="blank.html">Blank Page</a>
                                </li>
                                <li>
                                    <a href="login.html">Login Page</a>
                                </li>
                            </ul>
                            
                        </li>
                    </ul>
                </div>
                
            </div>
            
        </nav>

To dynamically add a new menu (drop down) item I added a click event handler as below.

	$("#navbar_brand").click(function(){

		$("#side-menu").append('<li><a href="#"><i class="fa fa-files-o fa-fw"></i> TEST Pages<span class="fa arrow"></span></a><ul class="nav nav-second-level"><li><a href="blank.html">Blank Page</a></li><li><a href="login.html">Login Page</a></li></ul></li>');
	});
	
The new menu item appears but doesnt toggle as the original 'Samples Pages menu'. This should work right?

TIA

des

* Updated *

Find below the html code for the issue

	<!DOCTYPE html>
	<html lang="en">

	<head>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">

		<title>SB Admin 2 - Bootstrap Admin Theme</title>

		
		<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

		
		<link href="vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

		
		<link href="dist/css/sb-admin-2.css" rel="stylesheet">

		
		<link href="vendor/morrisjs/morris.css" rel="stylesheet">

		
		<link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

		
		
		
	</head>

	<body>

		<div id="wrapper">

			
			<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#" id="navbar_brand">SB Admin v2.0</a>
				</div>
				

				<ul class="nav navbar-top-links navbar-right">
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
						</a>
						<ul class="dropdown-menu dropdown-user">
							<li>
								<a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
							</li>
						</ul>
						
					</li>
					
				</ul>
				

				<div class="navbar-default sidebar" role="navigation">
					<div class="sidebar-nav navbar-collapse">
						<ul class="nav" id="side-menu">
							<li>
								<a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
							</li>
							<li>
								<a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
								<ul class="nav nav-second-level">
									<li>
										<a href="blank.html">Blank Page</a>
									</li>
									<li>
										<a href="login.html">Login Page</a>
									</li>
								</ul>
								
							</li>
						</ul>
					</div>
					
				</div>
				
			</nav>

			<div id="page-wrapper">
				<div class="row">
					<div class="col-lg-12">
						<h1 class="page-header">Dashboard</h1>
					</div>
					
				</div>
				
			

				<div class="row">
					<div class="col-lg-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								Hover Rows
							</div>
							
							<div class="panel-body">
								<div class="table-responsive">
									<table class="table table-hover">
										<thead>
											<tr>
												<th>#</th>
												<th>First Name</th>
												<th>Last Name</th>
												<th>Username</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td>1</td>
												<td>Mark</td>
												<td>Otto</td>
												<td>@mdo</td>
											</tr>
											<tr>
												<td>2</td>
												<td>Jacob</td>
												<td>Thornton</td>
												<td>@fat</td>
											</tr>
											<tr>
												<td>3</td>
												<td>Larry</td>
												<td>the Bird</td>
												<td>@twitter</td>
											</tr>
										</tbody>
									</table>
								</div>
								
							</div>
							
						</div>
						
					</div>
					
		 
				</div>
				
			
			</div>
			
			

		</div>
		

		
		<script src="vendor/jquery/jquery.min.js"></script>

		
		<script src="vendor/core/js/common.js"></script>	

		
		<script src="vendor/metisMenu/metisMenu.min.js"></script>

		
		<script src="dist/js/sb-admin-2.js"></script>

		
		<script src="vendor/bootstrap/js/bootstrap.min.js"></script>

		
		
		<script>
		
		$( window ).on('load', function() {
			console_log("page loadedd");
				
			$(window).ready(function(){
				console_log("page ready");
				
			});		
		});

		
		$("#navbar_brand").click(function(){
			console_log("test");
			
			$("#side-menu").append('<li><a href="#"><i class="fa fa-files-o fa-fw"></i> TEST Pages<span class="fa arrow"></span></a><ul class="nav nav-second-level"><li><a href="blank.html">Blank Page</a></li><li><a href="login.html">Login Page</a></li></ul></li>');
			
			
		});
		
		</script>
	</body>
	</html>

**Comment by deslikespizza** [comment]
A colleague pointed out the solution today. Add the following after appending menu items $('#side-menu').metisMenu();

**Comment by hadifikri** [comment]
After looking everywhere .........

**Comment by davidtmiller** [comment]
This is no longer relevant after the version 4 release - but thanks for the answer here @deslikespizza
