### ISSUE TITLE
Is this template is build by bootstrap 4.0? Why i check bootstrap.js it show version v3.3.7

### ISSUE THREAD

**Issue by woonsan0619** [BlackrockDigital/startbootstrap-sb-admin-2#196]

**Comment by larrybahr** [comment]
Any idea when this will be updated to Bootstrap 4?

**Comment by pechar** [comment]
I just spent half a day upgrading to this because of bootstrap 4. At https://startbootstrap.com/template-overviews/sb-admin-2/ it says:

> Fully responsive HTML template created with Bootstrap 4

This however is not so. I'd recommend updating that info. Pretty misleading. 

On another note this is a great template. It's very useful.

**Comment by johnsnook** [comment]
If it's not bootstrap 4, dont say it is.  I also wasted time on this before realizing I had been mislead.  Bummer.

**Comment by ComputingFroggy** [comment]
+1

**Comment by acfatah** [comment]
I had been mislead too. Please update it to bootstrap 4.0 or update the info at [https://startbootstrap.com/template-overviews/sb-admin-2/](https://startbootstrap.com/template-overviews/sb-admin-2/).

Very nice template by the way.

**Comment by tmartis** [comment]
Any news if and when this will happen?

**Comment by ayningcao** [comment]
I saw SB Admin use Bootstrap 4.0, any differences between SB Admin and SB Admin 2?

**Comment by jondavis0787** [comment]
https://github.com/jondavis0787/sb-admin-2-bs4

**Comment by wamcvey** [comment]
Just another frustrated user chiming in to say time was wasted trying to debug a template that claimed it was Bootstrap4 only to actually be Bootstrap3. I truly appreciate the work that went into the template and it being available to the public, but I wish the documentation on the page (which claims it's bootstrap 4) were updated to reflect reality (even better, if the template were updated by the maintainer to actually live up to the bootstrap 4 claim). Thanks @jondavis0787 for your fork. Any thoughts in issuing a pull request so the original maintainer can integrate your changes?

**Comment by Fvdp** [comment]
Nice template but please update the documentation that says "Bootstrap 4", it is not !

**Comment by jondavis0787** [comment]
> Nice template but please update the documentation that says "Bootstrap 4", it is not !
> https://github.com/dpwilhelmsen/sb-admin-2-bootstrap-4

Use https://github.com/jondavis0787/sb-admin-2-bs4 This is a upgraded version note that this is fully created by StartBootstrap. With that said I thought it would be nice for someone to have a updated copy.

**Comment by davidtmiller** [comment]
Today is the day - Bootstrap 4 and a completely refactored layout and design is here with the version 4.0.0 update!
