### ISSUE TITLE
Page wrapper height is not recalculated on sidebar expanding

### ISSUE THREAD

**Issue by ivansammartino** [BlackrockDigital/startbootstrap-sb-admin-2#199]
The `#page-wrapper` min-height is calculated only on load and window resize, but not when expanding sidebar items, resulting in wrong background color: please see attached video

[Video file](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/files/1781336/bug.zip)

Please, can you fix this? Thank you

**Comment by Frank-Mertens** [comment]
(function (window, document, $) {
    function calcWidthAndHeight() {
        var topOffset = 50;
        var width = (window.innerWidth > 0) ? window.innerWidth : screen.width;
        if (width < 768) {
            $('div.navbar-collapse').addClass('collapse');
            topOffset = 100; // 2-row-menu
        } else {
            $('div.navbar-collapse').removeClass('collapse');
        }

        var height = ((window.innerHeight > 0) ? window.innerHeight : screen.height) - 1;
        height = height - topOffset;

        if (width >= 768) {
            var smHeight = $("#side-menu").outerHeight();
            if (smHeight > height) {
                height = smHeight;
            }
        }

        if (height < 1)
            height = 1;
        if (height > topOffset) {
            $("#page-wrapper").css("min-height", (height) + "px");
        }
    }

    $(window).on("load resize", function () {
        calcWidthAndHeight();
    });

    $(document).ready(function () {
        $('#side-menu').metisMenu({
            toggle: true,
            doubleTapToGo: false
        }).on('shown.metisMenu hidden.metisMenu', function (event) {
            calcWidthAndHeight()
        });

        var url = window.location;
        // var element = $('ul.nav a').filter(function() {
        //     return this.href == url;
        // }).addClass('active').parent().parent().addClass('in').parent();
        var element = $('ul.nav a').filter(function () {
            return this.href == url;
        }).addClass('active').parent();

        while (true) {
            if (element.is('li')) {
                element = element.parent().addClass('in').parent();
                if (element.is('li')) {
                    element.addClass('active');
                }
            } else {
                break;
            }
        }
    });
}(this, document, jQuery));

**Comment by Frank-Mertens** [comment]
Hi, this works for me...

```javascript
(function (window, document, $) {
    function calcWidthAndHeight() {
        var topOffset = 50;
        var width = (window.innerWidth > 0) ? window.innerWidth : screen.width;
        if (width < 768) {
            $('div.navbar-collapse').addClass('collapse');
            topOffset = 100; // 2-row-menu
        } else {
            $('div.navbar-collapse').removeClass('collapse');
        }

        var height = ((window.innerHeight > 0) ? window.innerHeight : screen.height) - 1;
        height = height - topOffset;

        if (width >= 768) {
            var smHeight = $("#side-menu").outerHeight();
            if (smHeight > height) {
                height = smHeight;
            }
        }

        if (height < 1)
            height = 1;
        if (height > topOffset) {
            $("#page-wrapper").css("min-height", (height) + "px");
        }
    }

    $(window).on("load resize", function () {
        calcWidthAndHeight();
    });

    $(document).ready(function () {
        $('#side-menu').metisMenu({
            toggle: true,
            doubleTapToGo: false
        }).on('shown.metisMenu hidden.metisMenu', function (event) {
            calcWidthAndHeight()
        });

        var url = window.location;
        // var element = $('ul.nav a').filter(function() {
        //     return this.href == url;
        // }).addClass('active').parent().parent().addClass('in').parent();
        var element = $('ul.nav a').filter(function () {
            return this.href == url;
        }).addClass('active').parent();

        while (true) {
            if (element.is('li')) {
                element = element.parent().addClass('in').parent();
                if (element.is('li')) {
                    element.addClass('active');
                }
            } else {
                break;
            }
        }
    });
}(this, document, jQuery));
```

**Comment by davidtmiller** [comment]
This is no longer handled by JavaScript in the version 4 build. Flexbox is now being used for the layout, which means the sidebar will resize dynamically with the size of the page content.
