### ISSUE TITLE
This states that it uses Bootstrap 4, but actually it uses Boostrap 3.3.7

### ISSUE THREAD

**Issue by 19007361** [BlackrockDigital/startbootstrap-sb-admin-2#202]

**Comment by tiesont** [comment]
There's an existing issue for this: #196

**Comment by 19007361** [comment]
Thanks, hope it gets updated soon. Would really like to use this template with my 4.0 projects.

**Comment by hvedemelsbof** [comment]
I wasted quite some time on this template before figuring that out as well...

**Comment by jondavis0787** [comment]
https://github.com/jondavis0787/sb-admin-2-bs4

**Comment by davidtmiller** [comment]
The new version 4 update now uses Bootstrap 4 and a completely refactored layout and design.
