### ISSUE TITLE
gulpfile.js missing part of code

### ISSUE THREAD

**Issue by alessandrotarparelli** [BlackrockDigital/startbootstrap-sb-admin-2#203]
Good evening at all developer.
I'm studying gulp and I'm changing the code of startbootstrap-sb-admin-2. I found in gulpfile.js file a possible wrong syntax, in particularly when use gulp.watch('js/*.js', ['minify-js']);. 
When I use gulp.watch do I should use this syntax: gulp.watch('files-to-watch', ['tasks', 'to', 'run']);?.
According to me the correct code could be this: 

// Dev task with browserSync
gulp.task('dev', ['browserSync', 'less', 'minify-css', 'js', 'minify-js'], function() {
    gulp.watch('less/*.less', ['less']);
    gulp.watch('dist/css/*.css', ['minify-css']);
    gulp.watch('js/*.js', ['js']);
    gulp.watch('dist/js/*.js', ['minify-js']);
    // Reloads the browser whenever HTML or JS files change
    gulp.watch('pages/*.html', browserSync.reload);
    gulp.watch('dist/js/*.js', browserSync.reload);
});

It's correct o I'm wrong?

I paste the complete original code: 

// Dev task with browserSync
gulp.task('dev', ['browserSync', 'less', 'minify-css', 'js', 'minify-js'], function() {
    gulp.watch('less/*.less', ['less']);
    gulp.watch('dist/css/*.css', ['minify-css']);
    gulp.watch('js/*.js', ['minify-js']);
    // Reloads the browser whenever HTML or JS files change
    gulp.watch('pages/*.html', browserSync.reload);
    gulp.watch('dist/js/*.js', browserSync.reload);
});

**Comment by davidtmiller** [comment]
This should be fixed in the version 4 update.
