### ISSUE TITLE
'active', 'in' class not work.

### ISSUE THREAD

**Issue by LeeHyun-A** [BlackrockDigital/startbootstrap-sb-admin-2#207]
nav-third-level

When window.location has query string, 'active' and 'in' addClass not work.

I fixed your code.
Please, show below difference code and answer to my question.

-- your code
    var url = window.location;
    // var element = $('ul.nav a').filter(function() {
    //     return this.href == url;
    // }).addClass('active').parent().parent().addClass('in').parent();
    var element = $('ul.nav a').filter(function() {
        return this.href == url;
    }).addClass('active').parent();

    while (true) {
        if (element.is('li')) {
            element = element.parent().addClass('in').parent();
        } else {
            break;
        }
    }

--  my code
    var url = window.location;
    var element = $('ul.nav a').filter(function() {

        return this.href == url.href.split('?')[0];
    }).addClass('active').parent();

    while (true) {
        if (element.is('li')) {
            element = element.parent().addClass('in').parent().addClass('active');
        } else {
            break;
        }
    }

**Comment by davidtmiller** [comment]
Active class detection via jQuery or JavaScript was removed in the version 4 build.

**Comment by NLeone** [comment]
> Active class detection via jQuery or JavaScript was removed in the version 4 build.

Sorry to comment here is that I'm a little desperate, I do not take in my project the active url in the menu navigation. How is it done now so you can automatically take the menu item with the active url? Please can you answer me thank you very much! Regards!
