### ISSUE TITLE
really needs angular like flexibility 

### ISSUE THREAD

**Issue by fenderrex** [BlackrockDigital/startbootstrap-sb-admin-2#208]
Really needs angular variable syntax where any visible features are exhibited 
example. I have altered most templates for python Flask template format where varables are inserted server side (xml is less fun to scrape)
for more infomation on [Flask](http://flask.pocoo.org/docs/1.0/tutorial/templates/)

Benifits go behond compatabilty for flask. 
To support power users without flexabilty of a real server 

`<title>{{someVar}}<title>`
 
 then import the varables from a JS script detailed here 

[getting started](https://angular.io/guide/template-syntax)

[tutorial](https://docs.angularjs.org/tutorial/step_02)

**Comment by davidtmiller** [comment]
The front end framework that is used with this theme is a decision that I leave to the developer. Since the theme is just HTML and CSS with a hint of jQuery, it should be relatively easy to port this into any framework. Going to close this one for now.
