### ISSUE TITLE
right-click reload bug?

### ISSUE THREAD

**Issue by Springshen** [BlackrockDigital/startbootstrap-sb-admin-2#209]
click   Multi-Level Dropdown/Second Level item   CRTL+R（ or mouse  right-click reload）, maybe  auto select Charts, UI Elements, and Sample Pages.    why??

**Comment by encoder1995** [comment]
Hi @Springshen , I'd like to work on this issue.

**Comment by davidtmiller** [comment]
The sidebar was totally rebuilt in version 4.
