### ISSUE TITLE
Left Navigation

### ISSUE THREAD

**Issue by ejones31** [BlackrockDigital/startbootstrap-sb-admin-2#211]
I understand that the functionality between SB Admin's left nav will carry over into SB Admin 2 during the rewrite for BootStrap 4.
I'm not sure I'm reading that correctly, but can we please keep the styling and behavior of the Bootstrap 3 version of SB Admin 2's current Menu? Mainly, that once a menu is opened, showing the 2nd level, that it remains that way until another top level item is clicked.

**Comment by davidtmiller** [comment]
I have made this change for the new SB Admin 2. It uses the accordion structure so top level items close other top level items when clicked.
