### ISSUE TITLE
fa icons page gone

### ISSUE THREAD

**Issue by SoltauFintel** [BlackrockDigital/startbootstrap-sb-admin-2#215]
Where is the page https://blackrockdigital.github.io/startbootstrap-sb-admin-2/pages/icons.html ?

It would be nice if you can tell me where I can find the "fa" icons page.

**Comment by tiesont** [comment]
Other than the Font Awesome site itself? https://fontawesome.com/icons?d=gallery - I assumed it was removed because it's redundant.

**Comment by davidtmiller** [comment]
Yes @tiesont is correct. You can reference all of the icons on Font Awesome's website. Since they keep adding new icons so quickly it would be redundant to re-list them all on our page - and it would be a bit cumbersome to maintain.

**Comment by SoltauFintel** [comment]
I dont like the fontawesome.com site.
I was able to get the content here: https://web.archive.org/web/20180109144348/https://blackrockdigital.github.io/startbootstrap-sb-admin-2/pages/icons.html
:-)

**Comment by davidtmiller** [comment]
I will consider getting this added back in as a demo page.
