### ISSUE TITLE
fixed nav

### ISSUE THREAD

**Issue by lucabassplayer89** [BlackrockDigital/startbootstrap-sb-admin-2#219]
is it possible to have the sidebar on the left and on the top fixed?

**Comment by davidtmiller** [comment]
At the moment you can add the `.fixed-top` utility class to either and you will get this effect. Keep in mind the sidebar will now scroll though if the height goes past the viewport height - this would require adding the `overflow-y: auto` property to the CSS, but this will also make the dropdown's as items that pop out not work.
