### ISSUE TITLE
DataTables search and pagination unavailable when using two or more tables per page.

### ISSUE THREAD

**Issue by rgardiner2002** [BlackrockDigital/startbootstrap-sb-admin-2#241]
When I use multiple DataTables on one page the first table is perfectly fine however, the second table does not include the pagination, search bar and other features the other one has.

**Comment by ToeiRei** [comment]
it's a JS problem. You need to assign every table their own ID and tackle those individually.

**Comment by rgardiner2002** [comment]
> it's a JS problem. You need to assign every table their own ID and tackle those individually.

What else do I need to change other then the tables ID?

**Comment by ToeiRei** [comment]
Look at the table itself:
```
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
...
</table>
```

That's the JS making it come to live.
```
// Call the dataTables jQuery plugin
$(document).ready(function() {
  $('#dataTable').DataTable();
});
```

**Comment by rgardiner2002** [comment]
> Look at the table itself:
> 
> ```
> <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
> ...
> </table>
> ```
> 
> That's the JS making it come to live.
> 
> ```
> // Call the dataTables jQuery plugin
> $(document).ready(function() {
>   $('#dataTable').DataTable();
> });
> ```

Thanks! that works for me.

**Comment by ToeiRei** [comment]
feel free to close the issue.
