### ISSUE TITLE
Upgrade jQuery to avoid Prototype Pollution

### ISSUE THREAD

**Issue by AlexiZ** [BlackrockDigital/startbootstrap-sb-admin-2#248]
Hi,
First, thank you for your work, it saved me a lot of time and fits perfectly to my needs.
It looks like there is a moderate vulnerability in the jQuery dependency.

**Npm audit security report :**
_Moderate | Prototype Pollution
Package | jquery
Patched in | >=3.4.0
Dependency of | startbootstrap-sb-admin-2
Path | startbootstrap-sb-admin-2 > jquery
More info | https://npmjs.com/advisories/796_

Can you please update the jQuery dependency ? That would be awesome.

Have a good day.

PS : Same problem appears to some of your other repositories. I'll be reporting it when I see it.

**Comment by davidtmiller** [comment]
Updated, thanks for the message!
