### ISSUE TITLE
sidebar broken

### ISSUE THREAD

**Issue by fiha8** [BlackrockDigital/startbootstrap-sb-admin-2#298]
Hello, please anyone knows what could be wrong with my sidebar? I put all content to my MVC project, set correct paths...not working. Downloaded template works well on my screen, in MVC project not.

![screen](https://user-images.githubusercontent.com/56687658/67018067-f5edbf80-f0fa-11e9-99f0-10d5a2912738.jpg)

**Comment by tiesont** [comment]
Screenshots are nice for illustrating the problem, but lacking the specific HTML you're using, I doubt anyone could really help all that much.
