### ISSUE TITLE
[Not a bug] - Why bs and sb-admin-2 css in single file?

### ISSUE THREAD

**Issue by iyilm4z** [BlackrockDigital/startbootstrap-sb-admin-2#315]
I'm used to see bs and admin css files separated. That's why we import these css files separately or we could be using cdn. 
As you can see [sb-admin-2.css](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/blob/master/css/sb-admin-2.css) contains also bs css. Nowadays i see bs with custom styles in a single merged file. AdminLTE also does the same.
Why?

**Comment by tiesont** [comment]
Most likely? That CSS file is built from this template's Sass file, here: https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/blob/master/scss/sb-admin-2.scss

If you inspect that file, at [line 2](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/blob/60d24312ca1c3d75738d2b40e552a0495e53dda6/scss/sb-admin-2.scss#L2) you'll see this:

```css
@import "variables.scss";
```

followed by this at line 5:

```css
@import "../vendor/bootstrap/scss/bootstrap.scss";
```

Line 5 pulls in Bootstrap's Sass file, so the generated CSS file is also going to include Bootstrap. The `variables.scss` file contains overrides for some of Bootstrap's variables, which is easier than trying to add overriding rules in a normal CSS file (and is actually the [method recommended by the Bootstrap team](https://getbootstrap.com/docs/4.4/getting-started/theming/)).

**Comment by iyilm4z** [comment]
@tiesont thanks! i got it now. It's related to how b4's recommended way of theming.
