### ISSUE TITLE
DataTables not loaded in linux

### ISSUE THREAD

**Issue by flik** [BlackrockDigital/startbootstrap-sb-admin-2#39]
You have used Capital letters in the footers and your folder names are in small letters. 

   <script src="../bower_components/DataTables/media/js/jquery.dataTables.min.js"></script>

I have fixed at my end but please fix this in your repo. 
   <script src="../bower_components/datatables/media/js/jquery.dataTables.min.js"></script>

**Comment by marcelod** [comment]
https://github.com/IronSummitMedia/startbootstrap-sb-admin-2/pull/42

**Comment by grimmdude** [comment]
#1

**Comment by flik** [comment]
This issue must be fix but I think, still not pushed... :(
