### ISSUE TITLE
Wrong Case in <!-- DataTables JavaScript --> 

### ISSUE THREAD

**Issue by fguilhaumon** [BlackrockDigital/startbootstrap-sb-admin-2#41]
The path to the "jquery.dataTables.min.js" as a mistake : 

it reads : 
src="../bower_components/DataTables/media/js/jquery.dataTables.min.js"

but should be:
src="../bower_components/datatables/media/js/jquery.dataTables.min.js"

without any capital letter in "datatables"

Hope this help.

**Comment by davidtmiller** [comment]
I'll hit this soon, thanks for pointing this out.

**Comment by davidtmiller** [comment]
Should be fixed.
