### ISSUE TITLE
Would you add a Sass version?

### ISSUE THREAD

**Issue by stevenjlho** [BlackrockDigital/startbootstrap-sb-admin-2#46]
I like Sass more than Less. I hope that startbootstrap-sb-admin-2 have a sass version. Would you have a plan to do this?

**Comment by sman591** [comment]
I too would love a Sass version, all my projects are built with Sass

**Comment by hurrycaner** [comment]
Bootstrap 4 is comming with Sass, maybe we get lucky :)

**Comment by davidtmiller** [comment]
In the future SASS is definitely part of the plan. This themes next update will include (ideally) Gulp tasks to run everything, npm for all of the dev dependencies, LESS and SASS versions, a better side menu, and some other enhancements as I see fit. Perhaps some UI kits to go with it, but those might just be in their own repos actually...

Keeping this open as a reminder, thanks everyone!

**Comment by davidtmiller** [comment]
Gulp tasks are done, and Bootstrap 4 is going to be build with SASS over LESS so I will be defaulting to SASS with the Bootstrap 4 version of SB Admin 2 and having an alternate LESS version.
