### ISSUE TITLE
div in tables.html DataTables example contains css class typo

### ISSUE THREAD

**Issue by epalm** [BlackrockDigital/startbootstrap-sb-admin-2#47]
http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/pages/tables.html line 392

The `dataTable_wrapper` class doesn't exist, so

    <div class="dataTable_wrapper">

should be

    <div class="dataTables_wrapper">

**Comment by davidtmiller** [comment]
I'll check it out, thanks.

**Comment by davidtmiller** [comment]
Neither class exists actually. I guess I planned to use that for something but never did. I just removed it in #136
