### ISSUE TITLE
bower_components unnecessary

### ISSUE THREAD

**Issue by erayaydin** [BlackrockDigital/startbootstrap-sb-admin-2#49]
I think, **bower_components** will added to .gitignore file. Because its unnecessary. We can download this components with `bower.json`

**Comment by erayaydin** [comment]
Also, a gruntfile will good for compiling components to dist

**Comment by challgren** [comment]
Due to the way IronSummitMedia wants the repo to work. This is not a viable fix since bower_components needs to be included in the repo so the gh-pages can display the demo.

**Comment by davidtmiller** [comment]
I may create a gulp task to copy dev dependencies to a vendor directory from bower_components (or node_modules because I'll be switching to npm here soon) so the dev dependencies will be included with the theme, but not alongside the template core files.

**Comment by davidtmiller** [comment]
This is now taken into consideration. There's a `vendor` directory that has all of the third party dependencies in it. The `bower_components` directory was added to `.gitignore` and there is a new Gulp task to take the necessary dist files from `bower_components` and put them into `vendor`.

This removed a lot of unnecessary files that are included with the template.

Users can also run `bower install` if they want to pull the files in their own way, but the `vendor` library has everything that's needed.
