### ISSUE TITLE
Documentation for use?

### ISSUE THREAD

**Issue by unifrancouni** [BlackrockDigital/startbootstrap-sb-admin-2#51]

**Comment by challgren** [comment]
Its a theme, take and choose what you want to use. There's no real documentation since it's designed for people to cut up and customize to their liking.

**Comment by ORESoftware** [comment]
on this subject, for newbs, it would be cool to demonstrate how to install with bower and then use in a project. basically, a sample project that actually uses the them would help. right? ow, great work and thank you.

**Comment by banzo** [comment]
+1

**Comment by davidtmiller** [comment]
I will get some documentation written with some usage instructions in the near future when I make some improvements to this template. Thanks.

**Comment by Firestorm-Graphics** [comment]
i understand this is a framework but documentation on available functionality and examples would defo be so usefull. bootstrap docs are a good example. it doesnt just tell you its also shows you

**Comment by eryshev** [comment]
+1
