### ISSUE TITLE
Version mismatch with Bower installation

### ISSUE THREAD

**Issue by evolucionapp** [BlackrockDigital/startbootstrap-sb-admin-2#54]
There is a "mismatch" message when installing with Bower:

    bower startbootstrap-sb-admin-2#*         mismatch Version declared in the json (1.0.4) is different than the resolved one (1.0.6)

Perhaps, this is the reason:
![capture01](https://cloud.githubusercontent.com/assets/763974/7083350/3f766210-df26-11e4-9771-a967567a988f.PNG)

**Comment by challgren** [comment]
I believe this was fixed with v1.0.7 however this issue may crop up again in the future.

**Comment by jeanphilippelevy** [comment]
Same problem with 1.0.8 -> mismatch Version declared in the json (1.0.7) is different than the resolved one (1.0.8)

**Comment by davidtmiller** [comment]
Yes I'll have to look into this and update it for the short term.

**Comment by davidtmiller** [comment]
Reference #130 for more info on this
