### ISSUE TITLE
lots of HTML parsing errors when combined with Thymleaf 

### ISSUE THREAD

**Issue by yarix** [BlackrockDigital/startbootstrap-sb-admin-2#56]
when taking this template to Thymleaf framework (http://www.thymeleaf.org/) then many errors are reported by Thymleaf.
most errors are for not closing tags.
for example 
```html
<meta charset="utf-8"> 
should be  
<meta charset="utf-8" />
``` and there are many more.

it would be great if the sb-admin-2 fixed that.

**Comment by challgren** [comment]
Since you are getting the errors and have the software, it maybe better for you to fix them and submit a pull request. Without being able to reproduce the errors it would be impossible for everyone to fix them all.

**Comment by yarix** [comment]
I hope i did the "pull request" right, please review #57 

I've tested #57 locally, with Spring and Thymleaf. All pages are rendered correctly.
