### ISSUE TITLE
No valid licenses found at the time of updating Bower WebJars

### ISSUE THREAD

**Issue by anand-singh** [BlackrockDigital/startbootstrap-sb-admin-2#69]
Failed!
No valid licenses found. Detected licenses: Apache
The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1
License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo.
Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.
           
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

**Comment by anand-singh** [comment]
Hi @challgren and @davidtmiller ,

could you please look into this

Thanks,
Anand

**Comment by davidtmiller** [comment]
I'll have to look into this and make sure everything gets updated to MIT.

**Comment by davidtmiller** [comment]
Everything out there should be MIT at this point unless they aren't auto updating. I will continue to make sure everything gets updated though, but I am closing this issue for now!
