### ISSUE TITLE
Having trouble locating HTML for...

### ISSUE THREAD

**Issue by ORESoftware** [BlackrockDigital/startbootstrap-sb-admin-2#73]
I am having trouble locating the HTML templates for this

http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/pages/forms.html

I installed via Bower but I simply can't find the html in the installation that pertains to forms.html

what am I doing wrong? thx

**Comment by ORESoftware** [comment]
am I right when I say that it appears that the HTML for admin-2 is actually located in the admin-1 project?

https://github.com/IronSummitMedia/startbootstrap-sb-admin

I have to say that, if this is the case, unfortunately this is very confusing, it took me an hour of poking around to discover this.

is this correct?

**Comment by davidtmiller** [comment]
SB Admin and SB Admin 2 are different templates. SB Admin 2's HTML files are located here: https://github.com/IronSummitMedia/startbootstrap-sb-admin-2/tree/gh-pages/pages. If you download the template you will see a pages directory, that's where your HTML files are for this one. Hopefully this helps!

**Comment by nelson6e65** [comment]
@ORESoftware When you install via bower, `pages` directory is ignored:

```js
"ignore": [
  "**/.*",
  "node_modules",
  "bower_components",
  "test",
  "tests",
  "pages",
  "index.html",
  "/js"
]
```
