### ISSUE TITLE
bootstrap version?

### ISSUE THREAD

**Issue by joeaudette** [BlackrockDigital/startbootstrap-sb-admin-2#78]
I notice some commit descriptions suggest that bootstrap 3.3.5 is supported but the bower.json file references 3.3.1.
Can you clarify if this supports bootstrap 3.3.5 or not? Does the bower.json file need to be updated?

**Comment by user501254** [comment]
It shouldn't make a difference at all since [Bootstrap](https://github.com/twbs/bootstrap#versioning) uses [Semantic Versioning](http://semver.org/). So two versions of 3.3.x will be mostly compatible with each other as the newer one would only have bug fixes and no change to the UI elements.

**Comment by davidtmiller** [comment]
I'll be hitting all of the templates soon enough with a Bootstrap 4 update as well!
