### ISSUE TITLE
ui-bootstrap update

### ISSUE THREAD

**Issue by newmesiss** [BlackrockDigital/startbootstrap-sb-admin-2#81]
thanks for this great repository, you may want to see if ui-bootstrap update to 14.0.2? and not cause problems

**Comment by davidtmiller** [comment]
I'll check into it. Everything will be blown up shortly and updated to Bootstrap 4 though so I am not making major updates to themes and templates at the moment, I'm just working locally on getting everything Bootstrap 4 ready!
