### ISSUE TITLE
Disable automatic sidebar active state

### ISSUE THREAD

**Issue by markwalet** [BlackrockDigital/startbootstrap-sb-admin-2#84]
Is there a way to disable the automatic addition of the active class to a navigation item?
I would like to use my own logic.

**Comment by herko** [comment]
It happens in `sb-admin.js` file:

```javascript
...
var url = window.location;
var element = $('ul.nav a').filter(function() {
    return this.href == url || url.href.indexOf(this.href) == 0;
}).addClass('active').parent().parent().addClass('in').parent();
if (element.is('li')) {
    element.addClass('active');
}
```

Basically, it sets `.active` class to anchors where the `window.location` matches their `href` parameter, which is nice. What I don't like is that it sets `.active` class when `href="#"` which is commonly used. If that is your case, You can either modify the script condition, or change the parameter to `href="#!"`.

**Comment by davidtmiller** [comment]
Thanks @herko
