### ISSUE TITLE
Fixed width version?

### ISSUE THREAD

**Issue by kspearrin** [BlackrockDigital/startbootstrap-sb-admin-2#86]
Does there exist a version out there that uses a fixed width container for this theme?

**Comment by davidtmiller** [comment]
No unfortunately that doesn't exist with this theme. I will look into it for the future though.

**Comment by alebak** [comment]
I've solved it.

Only add this in sb-admin-2.css or sb-admin-2.less:

`
.navbar-static-top {
position: fixed;
 width: 100%;
}`

And modify:

`@media(min-width:768px) {
    #page-wrapper {
        position: inherit;
        margin: 0 0 0 250px;
        padding: 30px 30px;
        border-left: 1px solid #e7e7e7;
    }
}
`

**Comment by davidtmiller** [comment]
Thanks for the contribution @alebak
