### ISSUE TITLE
how to use with multiple pages?

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [BlackrockDigital/startbootstrap-sb-admin-2#87]
I would like to use the template for multi page project. 
I am unclear as to how can I have multiple pages. 
looking at the demo, I can see each page redefined the head with all the scripts. same goes for the menu. 

do I need to use some kind of a generator? or copy paste manually? I am unclear as to how this template supports multiple pages and would appreciate it if you elaborated on the topic.

**Comment by davidtmiller** [comment]
You would need to use a JavaScript front end framework.
