### ISSUE TITLE
iOS Safari Modals Not Showing When in Datatable

### ISSUE THREAD

**Issue by kennai33** [BlackrockDigital/startbootstrap-sb-admin-2#9]
In IOS Safari:

When attempting to launch a modal that is with in a datatable, the page dims as designed but the modal does not pop up.

It looks like the modal is being trapped in the datatable container.

This is happening on Safari on iOS.

Functionality works on Chrome Desktop.

**Comment by EriksonEnterprises** [comment]
> After further debugging, it looks like the issue is with bootstraps `<div class="table-responsive">`. When removed the modal popups up fine in iOS Safari.

Yes that works but then the scroll of the table (if you have a lot of columns) is gone and the whole page scrolls instead of just the table itself...

**Comment by EriksonEnterprises** [comment]
This is my workaround that seems to work okay:

I replaced:

`<div class="table table-responsive">`

with:

`<div class="table" style="overflow: auto;">`

This maintained the correct scrolling effects while also allowing apple devices to open modals within a table
