### ISSUE TITLE
Datatables > responsive

### ISSUE THREAD

**Issue by S-teffi** [BlackrockDigital/startbootstrap-sb-admin-2#90]
Hello my dears

you have created a really great template! Thumbs up! (:

I would like to use the table "Data Tables Advanced Tables": the first table of the page:
http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/pages/tables.html (pic 1)

But the table is not responsive (pic 2). So I have switched the class to "table-responsive" (instead of  "dataTable_wrapper"). The table is now responsive, but it always appears a horizontal scroll bar (even with a large monitor). (pic 3) Is this a bug?

Can you help me and tell me how I get the bar off / or that it appears only on smaller resolutions?

Thanks and best regards
Steffi

![pic 1](https://cloud.githubusercontent.com/assets/13656482/12110227/40da9066-b38a-11e5-8c32-acc6b37a3496.JPG)
![pic 2](https://cloud.githubusercontent.com/assets/13656482/12110228/4406d600-b38a-11e5-952c-f3b0498ea8c2.JPG)
![pic 3](https://cloud.githubusercontent.com/assets/13656482/12110233/4da095d4-b38a-11e5-9dc0-35e02ac20507.JPG)

**Comment by krzysiekpiasecki** [comment]
Have a look at #93 #94 #95. Change your source code to fix the responsive mode.

**Comment by krzysiekpiasecki** [comment]
Apply #96 patch to fix responsive example

**Comment by S-teffi** [comment]
Thanks for your fast help!

Now only the search-bar is still to long. (see pic1) Can you please tell me which code snippet I have to change?
![pic1](https://cloud.githubusercontent.com/assets/13656482/12165003/4c6818e0-b51a-11e5-852a-6954f712f93d.JPG)

At low resolutions I can't see all columns (only 2 of 5 - see pic1). Nice feature, but I need all columns at low resolutions, too. Can you please tell me how I can show all columns at low resolution? (with scrollbars)

Thanks and best regards, Steffi (:

**Comment by S-teffi** [comment]
Can anyone give me a hint?

**Comment by krzysiekpiasecki** [comment]
You may try dirty hacks. For example for search input:

```js

jQuery('.dataTables_filter label').after(
    jQuery('.dataTables_filter label input[type="search"]').detach()
);

```

**Comment by S-teffi** [comment]
oh okay thanks! 

And for the "show-not-all-coulumns-problem" at low screen resolutions there are no simple solution or can you help me in this case, too?
If not, then I'll have to live with the ugly bar (even with large screen resolution). (see pic 3 from first post)

Thanks and best regards, Steffi (:

**Comment by davidtmiller** [comment]
I believe this fix got merged, so I'm closing this for now.
